#+TITLE: Documentation of 'Book My Show' Web App
#+AUTHOR: Ravsimar Singh Sodhi, Anish Gulati, Kunal Garg

* Introduction
This file aims to explain the over-all working and design of our team's web app -
Book My Show.


* Overview
** Description
Build a movie booking system similar to that of Bookmyshow.
 
** Functionality
- Has a listing of upcoming/present movies.
- User can select a movie and a particular date and time in a particular theatre.
- The listing of movies is dynamic - adding or removing movies is handled from the database by the admin.
- User has a profile page to view his/her booking history.


* Application
** Data Schema
The database consists of some ordered tables to store information. These are:
(A more detailed description of models and controllers is linked in the headings)

+ [[./app/movie/movie.org][Movie]] :: contains the all movies of the database.
+ [[./app/auditorium/auditorium.org][Auditorium/Theatre]] :: contains all Theatres of the database.
+ [[./app/screening/screening.org][Screening]] :: contains all shows which were,are or will be aired in the theatres.
+ [[./app/seat/seat.org][Seat]] :: contains the seats and their costs according to the theatre.
+ [[./app/booking/booking.org][Booking]] :: contains all the bookings done by users.
+ [[./app/user/user.org][User]] :: contains the details of the user.

Apart from these basic database tables, some more classes and methods had to be defined.
+ [[./app/helper/helper.org][Helper]] :: contains helper functions for proper functioning of the app.

** Designing 
The first step while building this app was having a flexible but firm idea of the
database which would store the neccessary information for the functioning of the web
app.Many minor changes transpired in the schema along the way as we built our application.

We first built the database tables in python using flask sqlalchemy. Simultaneously,
we built some html webpages to have a better idea of the functionality of the application
and whether the database would suffice to provide the information in a well-ordered
manner as would be needed.

Linking the database with the front-end with javascript lead to an initial working
application. However, being only an initial working model, it had many bugs and
thus, after refining the front-end and the back-end as well, our final web application
was built.


 
